import notebookImg from "../assets/notebook.png";

export const styles = {
  page: {
    minHeight: "100vh",
    background: "linear-gradient(#cfe2f2, #f7e4bf)",
    padding: "40px 16px",
    fontFamily: "system-ui, -apple-system, Segoe UI, Roboto, sans-serif",
    color: "#4a3a2a",
  },
  container: { maxWidth: 1050, margin: "0 auto", textAlign: "center" },
  header: {
    marginBottom: 28,
    position: "relative",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    paddingTop: 20,
  },
  topRightActions: { position: "absolute", top: 0, right: 0, display: "flex", gap: 16 },
  title: { fontSize: 64, margin: 0, letterSpacing: 1 },
  newEntryBtn: {
    marginTop: 16,
    padding: "12px 28px",
    borderRadius: 14,
    border: "2px solid rgba(0,0,0,0.15)",
    background: "#f4b24f",
    color: "#3b2a1d",
    fontWeight: 700,
    cursor: "pointer",
    boxShadow: "0 6px 0 rgba(0,0,0,0.12)",
  },
  today: { marginTop: 14, opacity: 0.9 },
  topCarousel: { display: "flex", alignItems: "center", justifyContent: "center", gap: 14, marginTop: 22 },
  arrowBtn: {
    width: 44,
    height: 44,
    borderRadius: 999,
    border: "1px solid rgba(0,0,0,0.12)",
    background: "rgba(255,255,255,0.65)",
    cursor: "pointer",
    fontSize: 22,
  },
  cardsRow: { display: "flex", gap: 16, overflow: "hidden", padding: 6 },
  card: {
    width: 180,
    background: "rgba(255,255,255,0.75)",
    border: "1px solid rgba(0,0,0,0.12)",
    borderRadius: 14,
    padding: 10,
    boxShadow: "0 10px 20px rgba(0,0,0,0.08)",
  },
  thumb: {
    position: "relative",
    borderRadius: 12,
    overflow: "hidden",
    height: 120,
    background: "#fff",
    border: "1px solid rgba(0,0,0,0.08)",
  },
  thumbPlaceholder: {
    width: "100%",
    height: "100%",
    background: "linear-gradient(135deg, rgba(77,149,142,0.2), rgba(244,178,79,0.25))",
  },
  cardActions: { position: "absolute", right: 10, bottom: 10, display: "flex", gap: 8 },
  iconBtn: {
    width: 34,
    height: 34,
    borderRadius: 999,
    border: "1px solid rgba(0,0,0,0.12)",
    background: "rgba(255,255,255,0.85)",
    cursor: "pointer",
  },
  cardDate: { marginTop: 10, fontSize: 14, opacity: 0.9 },
  monthCarouselWrap: { marginTop: 30, display: "flex", justifyContent: "center" },
  monthCarousel: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    background: "rgba(255,255,255,0.55)",
    border: "1px solid rgba(0,0,0,0.12)",
    borderRadius: 16,
    padding: "10px 12px",
    boxShadow: "0 10px 20px rgba(0,0,0,0.06)",
  },
  monthArrow: {
    width: 38,
    height: 38,
    borderRadius: 999,
    border: "1px solid rgba(0,0,0,0.12)",
    background: "rgba(255,255,255,0.75)",
    cursor: "pointer",
    fontSize: 18,
  },
  monthPills: { display: "flex", gap: 10, padding: "0 4px" },
  monthPill: {
    padding: "10px 14px",
    borderRadius: 12,
    border: "1px solid rgba(0,0,0,0.12)",
    background: "rgba(255,255,255,0.75)",
    cursor: "pointer",
    fontWeight: 600,
  },
  monthPillActive: { background: "#f4b24f" },
  parentBtn: {
    padding: "12px 18px",
    borderRadius: 14,
    border: "1px solid rgba(0,0,0,0.12)",
    background: "#f6efe7",
    color: "#245a52",
    fontWeight: 700,
    cursor: "pointer",
    boxShadow: "0 8px 18px rgba(0,0,0,0.12)",
  },
  logoutBtn: {
    padding: "12px 18px",
    borderRadius: 14,
    border: "1px solid rgba(0,0,0,0.12)",
    background: "#f6efe7",
    color: "#a3402c",
    fontWeight: 700,
    cursor: "pointer",
    boxShadow: "0 8px 18px rgba(0,0,0,0.12)",
  },
  titleRow: { display: "flex", alignItems: "center", justifyContent: "center", gap: 12 },
  avatarWrapper: { position: "relative", width: 100, height: 85 },
  avatarCircle: { width: 100, height: 100, borderRadius: "50%", background: "#eee", overflow: "hidden" },
  avatarImage: { width: "100%", height: "100%", objectFit: "cover" },
  avatarEditBtn: {
    position: "absolute",
    bottom: -8,
    right: -4,
    width: 24,
    height: 24,
    borderRadius: "50%",
    background: "#ffffff",
    border: "1px solid #ddd",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    boxShadow: "0 2px 6px rgba(0,0,0,0.15)",
    fontSize: 12,
  },
  hiddenFileInput: { display: "none" },
};

export const modalStyles = {
  backdrop: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.45)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 9999,
    padding: 16,
  },
  modal: { width: "min(560px, 92vw)" },
  notebook: {
    width: 520,
    aspectRatio: "2 / 3",
    backgroundImage: `url(${notebookImg})`,
    backgroundSize: "contain",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "center",
    position: "relative",
    paddingTop: 58,
    paddingRight: 54,
    paddingBottom: 90,
    paddingLeft: 92,
    display: "flex",
    flexDirection: "column",
  },
  date: { position: "absolute", top: 65, right: 56, fontSize: 14, opacity: 0.85 },
  field: { textAlign: "left" },
  label: { fontWeight: 700, fontSize: 18, marginBottom: 6 },
  titleInput: {
    width: "100%",
    height: 44,
    borderRadius: 12,
    border: "1px solid #d8cfc2",
    padding: "0 14px",
    fontSize: 16,
    background: "rgba(255,255,255,0.75)",
    outline: "none",
  },
  textarea: {
    width: "100%",
    height: 330,
    borderRadius: 12,
    border: "1px solid #d8cfc2",
    padding: 14,
    fontSize: 16,
    resize: "none",
    background: "rgba(255,255,255,0.75)",
  },
  photoRow: { display: "flex", gap: 14, justifyContent: "center", alignItems: "center", marginTop: 12 },
  actions: { display: "flex", justifyContent: "center", gap: 14, marginTop: 4 },
  primary: {
    minWidth: 160,
    padding: "10px 18px",
    borderRadius: 12,
    border: "1px solid rgba(0,0,0,0.2)",
    background: "#f4b24f",
    cursor: "pointer",
    fontWeight: 700,
  },
  secondary: {
    minWidth: 120,
    padding: "10px 18px",
    borderRadius: 12,
    border: "1px solid rgba(0,0,0,0.2)",
    background: "rgba(255,255,255,0.75)",
    cursor: "pointer",
    fontWeight: 700,
  },
  bottomSection: { marginTop: "auto" },
  photoSlot: {
    width: 70,
    height: 70,
    borderRadius: 16,
    background: "rgba(255,255,255,0.55)",
    border: "1px solid rgba(255,255,255,0.75)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    position: "relative",
    overflow: "hidden",
  },
  photoImg: { width: "100%", height: "100%", objectFit: "cover", display: "block" },
  photoRemoveBtn: {
    position: "absolute",
    top: 6,
    right: 6,
    width: 22,
    height: 22,
    borderRadius: 999,
    border: "none",
    background: "rgba(0,0,0,0.55)",
    color: "#fff",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 0,
  },
  plus: { fontSize: 26, lineHeight: 1, color: "rgba(0,0,0,0.55)", userSelect: "none" },
};